name: Github action
on: 
  push:
    branches:
      - dev
jobs:
  action-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        uses: actions/checkout@v6
      - name: print the index.html
        run: cat index.html
 

  
      
    
